# Dependabot configuration to update Monster dependencies

version: 2
updates:
# Enable version updates for cargo
- package-ecosystem: "cargo"
  # Look for `Cargo.toml` and `lock` files in the `root` directory
  directory: "/"
  # Check the crates.io registry for updates every day (weekdays)
  schedule:
    interval: "daily"
  commit-message:
    prefix: "chore: "
    include: "scope"
  # Update the Cargo.toml manifest file to relax
  # the version requirements
  versioning-strategy: auto
  # Specify labels for pull requests
  labels:
  - "cargo"
  - "dependencies"
