[package]
name = "monster"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>", "Fabian Nedoluha <monster@onders.org>"]
edition = "2018"
description = "Monster is a symbolic execution engine for 64-bit RISC-V code"

[dependencies]
goblin = "0.2"
byteorder = "1.3.4"
clap = "3.0.0-beta.2"
riscv-decode = { git = "https://github.com/cksystemsgroup/riscv-decode" }
petgraph = "0.5.1"
rand = "0.7.3"
boolector = { version = "0.4", git = "https://github.com/finga/boolector-rs", branch = "boolector-src", features = ["vendored"] }

[dev-dependencies]
serial_test = "0.4.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["user-hooks"]
