[package]
name = "monster"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>", "Fabian Nedoluha <monster@onders.org>"]
edition = "2018"
# TODO: improve description
description = "Monster engine."

[dependencies]
goblin = "0.2"
byteorder = "1.3.4"
clap = "3.0.0-beta.1"

[dev-dependencies]
serial_test = "0.4.0"

[features]
elf64 = []
