[package]
name = "monster"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>", "Fabian Nedoluha <monster@onders.org>"]
edition = "2018"
description = "Monster is a symbolic execution engine for 64-bit RISC-V code"

[dependencies]
goblin = "0.2"
byteorder = "1.3.4"
clap = "3.0.0-beta.1"
riscv-decode = "0.2.0"

[dev-dependencies]
serial_test = "0.4.0"

[features]
elf64 = []
