[package]
name = "monster"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>"]
edition = "2018"

[dependencies]
goblin = "0.2"
byteorder = "1.3.4"

[dev-dependencies]
serial_test = "0.4.0"

[features]
elf64 = []
