[package]
name = "utils"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>"]
edition = "2018"

[dependencies]
rayon = "~1.10.0"
tempfile = "~3.10.1"
which = "~4.4.2"
log = "~0.4.21"
env_logger = "~0.11.3"
