[package]
name = "utils"
version = "0.1.0"
authors = ["Christian Mösl <christian.moesl@live.at>"]
edition = "2018"

[dependencies]
rayon = "~1.5"
tempfile = "~3.3"
which = "~4.2"
log = "~0.4"
env_logger = "~0.9"
