name: Release

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
    release:
        name: Semantic Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                fetch-depth: 0
                persist-credentials: false

          - name: Install Rust Stable
            uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: Install Semantic Release for Rust
            uses: actions-rs/cargo@v1
            with:
                command: install
                args: semantic-release-rust --version 1.0.0-alpha.7

          # The release build is used in the Semantic Release step
          - name: Build
            uses: actions-rs/cargo@v1
            with:
                command: build
                args: --release

          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v2
            id: semantic
            with:
                semantic_version: 17.1.1
                extra_plugins: |
                    @semantic-release/exec@5.0
                    @semantic-release/git@9.0
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
